name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the site in the jekyll/builder container
      env:
        ADMIN_PASS: ${{ secrets.ADMIN_PASSWORD }} 
      run: |
        # Create _data folder locally first to avoid permission issues
        mkdir -p _data
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        -e ADMIN_PASS="$ADMIN_PASS" \
        jekyll/builder:latest /bin/bash -c "echo 'password: $ADMIN_PASS' > /srv/jekyll/_data/secrets.yml && jekyll build"
